Repository De-v-log/wasd, pull requests merged in 2024-10, with the labels that each got.

#13 [FEAT] API 요청시사용하기 위한 OAuth 권한 요청 API 생성
  src/main/java/com/wasd/config/security/OAuth2UserInfo.java
  src/main/java/com/wasd/config/security/OAuthTempController.java
  src/main/java/com/wasd/config/security/SecurityConfig.java
  src/main/java/com/wasd/gameInfo/controller/GameInfoController.java
Labels: 💻back-end, ✨feat

#14 [DOCS] ISSUE 템플릿 생성
  .github/ISSUE_TEMPLATE/1_feat.yml
  .github/ISSUE_TEMPLATE/2_bug.yml
  .github/ISSUE_TEMPLATE/9_etc.yml
  .github/pull_request_template.md
Labels: 📝docs

#15 [STYLE][REFACTOR] main 페이지 기본 구조 작성 / 회원가입 가입 확인 로직 변경
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/java/com/wasd/config/security/SecurityConfig.java
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/common/fragments/header.css
  src/main/resources/static/css/user/join.css
  src/main/resources/static/js/common/fragments/header.js
  src/main/resources/static/js/user/join.js
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/group/groupDetail.html
  src/main/resources/templates/pages/main.html
  src/main/resources/templates/pages/user/login.html
  src/main/resources/templates/pages/user/profileSetting.html
Labels: 🎨front-end, ♻ refactor

#19 [FEAT] 세션 DB 저장 및 로그인 페이지 redirect 수정
  build.gradle
  src/main/java/com/wasd/WasdApplication.java
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/java/com/wasd/config/security/CustomOAuth2User.java
  src/main/java/com/wasd/config/security/OAuth2UserInfo.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: ✅fixed

#26 [REFACTOR][STYLE] Root 경로 수정 / 에러 페이지 추가
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/java/com/wasd/config/CustomErrorController.java
  src/main/resources/application.yml
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/common/error.css
  src/main/resources/static/images/error_gameover.png
  src/main/resources/static/index.html
  src/main/resources/templates/common/error.html
Labels: 🎨front-end, ♻ refactor

#28 [FEAT][REFACTOR] 그룹 목록 조회 페이지 구현 & 회원가입 코드 리팩토링
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/common/fragments/header.css
  src/main/resources/static/css/fontawesome/all.min.css
  src/main/resources/static/css/group/group.css
  src/main/resources/static/css/user/join.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/common/fragments/header.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/user/join.js
  src/main/resources/static/js/user/joinCommon.js
  src/main/resources/static/js/user/profileSetting.js
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/group/groupNew.html
  src/main/resources/templates/pages/main.html
  src/main/resources/templates/pages/user/join.html
  src/main/resources/templates/pages/user/profileSetting.html
Labels: 🎨front-end, ✨feat, ♻ refactor

#29 [FEAT][REFACTOR] 그룹 생성 & 상세 보기 페이지 구현
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/common/fragments/header.css
  src/main/resources/static/css/group/group.css
  src/main/resources/static/css/group/groupDetail.css
  src/main/resources/static/css/group/groupNew.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/common/fragments/header.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupNew.js
  src/main/resources/static/js/user/joinCommon.js
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/group/groupDetail.html
  src/main/resources/templates/pages/group/groupNew.html
  src/main/resources/templates/pages/main.html
Labels: 🎨front-end, ✨feat, ♻ refactor

#32 [FEAT] 그룹게임정보 RestAPI 구현 & 그룹 정보 생성
  src/main/java/com/wasd/gameInfo/controller/GameInfoController.java
  src/main/java/com/wasd/gameInfo/dto/GroupGameInfoDto.java
  src/main/java/com/wasd/gameInfo/entity/GroupGameInfo.java
  src/main/java/com/wasd/gameInfo/repository/GroupGameInfoRepository.java
  src/main/java/com/wasd/gameInfo/service/GameInfoService.java
  src/main/java/com/wasd/group/controller/GroupController.java
  src/main/java/com/wasd/group/dto/GroupDto.java
  src/main/java/com/wasd/group/dto/GroupUserDto.java
  src/main/java/com/wasd/group/entity/Group.java
  src/main/java/com/wasd/group/entity/GroupUser.java
  src/main/java/com/wasd/group/repository/GroupRepository.java
  src/main/java/com/wasd/group/repository/GroupUserRepository.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/java/com/wasd/user/entity/User.java
Labels: 💻back-end, ✨feat
