Repository De-v-log/wasd, pull requests merged in 2024-11, with the labels that each got.

#33 [FEAT] 그룹 조회 기능, 그룹 생성 기능
  src/main/java/com/wasd/gameInfo/controller/GameInfoController.java
  src/main/java/com/wasd/gameInfo/repository/GroupGameInfoRepository.java
  src/main/java/com/wasd/gameInfo/service/GameInfoService.java
  src/main/java/com/wasd/group/controller/GroupController.java
  src/main/java/com/wasd/group/dto/GroupDto.java
  src/main/java/com/wasd/group/entity/Group.java
  src/main/java/com/wasd/group/repository/GroupUserRepository.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/resources/static/css/common/fragments/menu.css
  src/main/resources/static/css/group/group.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/common/fragments/header.js
  src/main/resources/static/js/common/fragments/menu.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupNew.js
  src/main/resources/static/js/user/join.js
  src/main/resources/static/js/user/joinCommon.js
  src/main/resources/static/js/user/profileSetting.js
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/fragments/menu.html
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/main.html
Labels: 💻back-end, 🎨front-end, ✨feat

#34 [FEAT] 그룹 상세정보 조회
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/resources/static/css/group/groupDetail.css
  src/main/resources/static/css/group/groupView.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/common/fragments/menu.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupView.js
  src/main/resources/templates/pages/group/groupDetail.html
  src/main/resources/templates/pages/group/groupView.html
Labels: 💻back-end, 🎨front-end, ✨feat

#35 [FEAT] 그룹채팅 1차 구현
  build.gradle
  src/main/java/com/wasd/chat/ChatController.java
  src/main/java/com/wasd/chat/ChatDto.java
  src/main/java/com/wasd/chat/ChatService.java
  src/main/java/com/wasd/chat/ChatUsers.java
  src/main/java/com/wasd/chat/ChatUsersRepository.java
  src/main/java/com/wasd/common/controller/CustomErrorController.java
  src/main/java/com/wasd/common/controller/OAuthTempController.java
  src/main/java/com/wasd/common/controller/PageController.java
  src/main/java/com/wasd/common/exception/ErrorCode.java
  src/main/java/com/wasd/common/exception/ErrorResponse.java
  src/main/java/com/wasd/common/exception/GlobalExceptionHandler.java
  src/main/java/com/wasd/common/exception/WasdException.java
  src/main/java/com/wasd/common/oauth/CustomOAuth2User.java
  src/main/java/com/wasd/common/oauth/OAuth2UserInfo.java
  src/main/java/com/wasd/common/oauth/OAuth2UserService.java
  src/main/java/com/wasd/config/GlobalExceptionHandler.java
  src/main/java/com/wasd/config/SecurityConfig.java
  src/main/java/com/wasd/config/WebSockectConfig.java
  src/main/java/com/wasd/gameInfo/controller/GameInfoController.java
  src/main/java/com/wasd/group/controller/GroupController.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/java/com/wasd/user/controller/UserController.java
  src/main/java/com/wasd/user/dto/UserDto.java
  src/main/java/com/wasd/user/service/UserService.java
  src/main/resources/static/cdn/css/dropzone.min.css
  src/main/resources/static/cdn/css/jquery-ui.css
  src/main/resources/static/cdn/css/slick.css
  src/main/resources/static/cdn/css/sweetalert2.min.css
  src/main/resources/static/cdn/css/toastr.min.css
  src/main/resources/static/cdn/js/dropzone.min.js
  src/main/resources/static/cdn/js/jquery-3.6.0.min.js
  src/main/resources/static/cdn/js/jquery-ui.js
  src/main/resources/static/cdn/js/slick.min.js
  src/main/resources/static/cdn/js/sockjs.js
  src/main/resources/static/cdn/js/stomp.min.js
  src/main/resources/static/cdn/js/sweetalert2.all.min.js
  src/main/resources/static/cdn/js/toastr.min.js
  src/main/resources/static/css/group/groupDetail.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/common/fragments/menu.js
  src/main/resources/static/js/common/util.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/pages/group/groupDetail.html
  src/main/resources/templates/pages/group/groupView.html
Labels: 💻back-end, ✨feat, ⚙️build, ♻ refactor

#37 [STYLE][CHORE] css 및 에러처리 수정
  src/main/java/com/wasd/common/controller/OAuthTempController.java
  src/main/java/com/wasd/common/oauth/OAuth2UserInfo.java
  src/main/java/com/wasd/gameInfo/service/GameInfoService.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/java/com/wasd/user/service/UserService.java
  src/main/resources/static/cdn/css/sweetalert2.min.css
  src/main/resources/static/cdn/js/sweetalert2.all.min.js
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/user/join.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupNew.js
  src/main/resources/static/js/user/join.js
  src/main/resources/static/js/user/joinCommon.js
  src/main/resources/static/js/user/profileSetting.js
  src/main/resources/templates/pages/group/group.html
Labels: ✅fixed

#38 [FEAT] 그룹 정보 조회 기능
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/resources/static/css/group/group.css
  src/main/resources/static/css/group/groupView.css
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupView.js
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/group/groupView.html
Labels: ✨feat, ✅fixed

#39 [FEAT] 그룹 추천 알고리즘 구현
  src/main/java/com/wasd/group/controller/GroupController.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/resources/static/css/common/common.css
  src/main/resources/static/css/group/groupDetail.css
  src/main/resources/static/js/common/fragments/menu.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupNew.js
  src/main/resources/templates/pages/group/group.html
  src/main/resources/templates/pages/group/groupDetail.html
  src/main/resources/templates/pages/group/groupNew.html
  src/main/resources/templates/pages/main.html
Labels: 💻back-end, 🎨front-end, ✨feat

#41 [FEAT] 그룹 나가기 기능
  src/main/java/com/wasd/common/exception/ErrorResponse.java
  src/main/java/com/wasd/group/controller/GroupController.java
  src/main/java/com/wasd/group/repository/GroupUserRepository.java
  src/main/java/com/wasd/group/service/GroupService.java
  src/main/resources/static/css/common/error.css
  src/main/resources/static/css/group/group.css
  src/main/resources/static/js/common/common.js
  src/main/resources/static/js/common/util.js
  src/main/resources/static/js/group/group.js
  src/main/resources/static/js/group/groupDetail.js
  src/main/resources/static/js/group/groupView.js
  src/main/resources/templates/pages/group/groupDetail.html
Labels: 💻back-end, ✨feat
